import { FaFileAlt, FaFileArchive, FaFilePdf } from "react-icons/fa";
import { RiApps2AiFill } from "react-icons/ri";
import { BiSolidVideos } from "react-icons/bi";
import { MdAudioFile } from "react-icons/md";
import { IoImage } from "react-icons/io5";

export const downloadData = [
  {
    id: 1,
    icon2: <FaFilePdf size={32} />,
    title: "QR Code Generator",
    path: "https://high-qr-code-generator.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "pdf", name: "PDFs" }],
  },
  {
    id: 2,
    icon2: <FaFilePdf size={32} />,
    title: "Color Palette Generator",
    path: "https://coolors.co/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "pdf", name: "PDFs" }],
  },
  {
    id: 3,
    icon2: <IoImage size={32} />,
    title: "HTML Formatter",
    path: "https://htmlformatter.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "img", name: "Image" }],
  },
  {
    id: 4,
    icon2: <IoImage size={32} />,
    title: "CSS Minifier",
    path: "https://cssminifier.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "img", name: "Image" }],
  },
  {
    id: 5,
    icon2: <IoImage size={32} />,
    title: "JavaScript Beautifier",
    path: "https://beautifier.io/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "img", name: "Image" }],
  },
  {
    id: 6,
    icon2: <FaFilePdf size={32} />,
    title: "JSON Formatter",
    path: "https://jsonformatter.org/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "pdf", name: "PDFs" }],
  },
  {
    id: 7,
    icon2: <FaFilePdf size={32} />,
    title: "Markdown Editor",
    path: "https://dillinger.io/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "pdf", name: "PDFs" }],
  },
  {
    id: 8,
    icon2: <FaFileAlt size={32} />,
    title: "Regex Tester",
    path: "https://regex101.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "document", name: "Document" }],
  },
  {
    id: 9,
    icon2: <FaFileAlt size={32} />,
    title: "Image Compressor",
    path: "https://tinypng.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "document", name: "Document" }],
  },
  {
    id: 10,
    icon2: <FaFileAlt size={32} />,
    title: "Online Stopwatch",
    path: "https://www.online-stopwatch.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "document", name: "Document" }],
  },
  {
    id: 11,
    icon2: <FaFileAlt size={32} />,
    title: "UUID Generator",
    path: "https://www.uuidgenerator.net/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "document", name: "Document" }],
  },
  {
    id: 12,
    icon2: <RiApps2AiFill size={32} />,
    title: "Lorem Ipsum Generator",
    path: "https://www.lipsum.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "app", name: "Apps" }],
  },
  {
    id: 13,
    icon2: <RiApps2AiFill size={32} />,
    title: "Password Generator",
    path: "https://passwordsgenerator.net/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "app", name: "Apps" }],
  },
  {
    id: 14,
    icon2: <RiApps2AiFill size={32} />,
    title: "Base64 Encoder/Decoder",
    path: "https://www.base64-image.de/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "app", name: "Apps" }],
  },
  {
    id: 15,
    icon2: <FaFileArchive size={32} />,
    title: "Unit Converter",
    path: "https://www.unitconverters.net/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "compress", name: "compress" }],
  },
  {
    id: 16,
    icon2: <FaFileArchive size={32} />,
    title: "Currency Converter",
    path: "https://www.xe.com/currencyconverter/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "compress", name: "compress" }],
  },
  {
    id: 17,
    icon2: <BiSolidVideos size={32} />,
    title: "IP Address Lookup",
    path: "https://www.whatismyip.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "video", name: "video" }],
  },
  {
    id: 18,
    icon2: <BiSolidVideos size={32} />,
    title: "Barcode Generator",
    path: "https://barcode.tec-it.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "video", name: "video" }],
  },
  {
    id: 19,
    icon2: <MdAudioFile size={32} />,
    title: "Text to Speech Converter",
    path: "https://ttsmp3.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "audio", name: "audio" }],
  },
  {
    id: 20,
    icon2: <MdAudioFile size={32} />,
    title: "Word Counter",
    path: "https://wordcounter.net/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "audio", name: "audio" }],
  },
];
