export const downloadData = [
  {
    id: 1,
    icon: "https://img.icons8.com/?size=48&id=LmcGmjPSQXSa&format=png",
    title: "QR Code Generator",
    path: "https://high-qr-code-generator.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "pdf", name: "PDFs" }],
  },
  {
    id: 2,
    icon: "https://img.icons8.com/?size=48&id=LmcGmjPSQXSa&format=png",
    title: "Color Palette Generator",
    path: "https://coolors.co/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "pdf", name: "PDFs" }],
  },
  {
    id: 3,
    icon: "https://img.icons8.com/?size=48&id=13917&format=png",
    title: "HTML Formatter",
    path: "https://htmlformatter.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "img", name: "Image" }],
  },
  {
    id: 4,
    icon: "https://img.icons8.com/?size=48&id=13917&format=png",
    title: "CSS Minifier",
    path: "https://cssminifier.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "img", name: "Image" }],
  },
  {
    id: 5,
    icon: "https://img.icons8.com/?size=48&id=13917&format=png",
    title: "JavaScript Beautifier",
    path: "https://beautifier.io/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "img", name: "Image" }],
  },
  {
    id: 6,
    icon: "https://img.icons8.com/?size=48&id=LmcGmjPSQXSa&format=png",
    title: "JSON Formatter",
    path: "https://jsonformatter.org/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "pdf", name: "PDFs" }],
  },
  {
    id: 7,
    icon: "https://img.icons8.com/?size=48&id=LmcGmjPSQXSa&format=png",
    title: "Markdown Editor",
    path: "https://dillinger.io/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "pdf", name: "PDFs" }],
  },
  {
    id: 8,
    icon: "https://img.icons8.com/?size=48&id=12053&format=png",
    title: "Regex Tester",
    path: "https://regex101.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "document", name: "Document" }],
  },
  {
    id: 9,
    icon: "https://img.icons8.com/?size=48&id=12053&format=png",
    title: "Image Compressor",
    path: "https://tinypng.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "document", name: "Document" }],
  },
  {
    id: 10,
    icon: "https://img.icons8.com/?size=48&id=12053&format=png",
    title: "Online Stopwatch",
    path: "https://www.online-stopwatch.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "document", name: "Document" }],
  },
  {
    id: 11,
    icon: "https://img.icons8.com/?size=48&id=12053&format=png",
    title: "UUID Generator",
    path: "https://www.uuidgenerator.net/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "document", name: "Document" }],
  },
  {
    id: 12,
    icon: "https://img.icons8.com/?size=48&id=fKXXelWgP1B6&format=png",
    title: "Lorem Ipsum Generator",
    path: "https://www.lipsum.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "app", name: "Apps" }],
  },
  {
    id: 13,
    icon: "https://img.icons8.com/?size=48&id=fKXXelWgP1B6&format=png",
    title: "Password Generator",
    path: "https://passwordsgenerator.net/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "app", name: "Apps" }],
  },
  {
    id: 14,
    icon: "https://img.icons8.com/?size=48&id=fKXXelWgP1B6&format=png",
    title: "Base64 Encoder/Decoder",
    path: "https://www.base64-image.de/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "app", name: "Apps" }],
  },
  {
    id: 15,
    icon: "https://img.icons8.com/?size=48&id=13411&format=png",
    title: "Unit Converter",
    path: "https://www.unitconverters.net/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "compress", name: "compress" }],
  },
  {
    id: 16,
    icon: "https://img.icons8.com/?size=48&id=13411&format=png",
    title: "Currency Converter",
    path: "https://www.xe.com/currencyconverter/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "compress", name: "compress" }],
  },
  {
    id: 17,
    icon: "https://img.icons8.com/?size=48&id=9a46bTk3awwI&format=png",
    title: "IP Address Lookup",
    path: "https://www.whatismyip.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "video", name: "video" }],
  },
  {
    id: 18,
    icon: "https://img.icons8.com/?size=48&id=9a46bTk3awwI&format=png",
    title: "Barcode Generator",
    path: "https://barcode.tec-it.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "video", name: "video" }],
  },
  {
    id: 19,
    icon: "https://img.icons8.com/?size=80&id=lSaOzJehYBsV&format=png",
    title: "Text to Speech Converter",
    path: "https://ttsmp3.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "audio", name: "audio" }],
  },
  {
    id: 20,
    icon: "https://img.icons8.com/?size=80&id=lSaOzJehYBsV&format=png",
    title: "Word Counter",
    path: "https://wordcounter.net/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "audio", name: "audio" }],
  },
];
